# Generated by Django 4.0 on 2025-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=270)),
                ('image', models.ImageField(upload_to='posts/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='ques',
            new_name='question',
        ),
    ]
