# Generated by Django 4.0 on 2025-04-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_communitypost_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image/'),
        ),
    ]
