# Generated by Django 4.0 on 2025-04-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_communitypost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='image',
        ),
    ]
