# Generated by Django 4.0 on 2025-04-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_communitypost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(default='abcd', upload_to='community_post/'),
            preserve_default=False,
        ),
    ]
