# Generated by Django 4.0 on 2025-04-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_communitypost_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
