# Generated by Django 4.0 on 2025-04-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_delete_communitypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommmunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=270, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
