# Generated by Django 4.0 on 2025-04-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_commmunitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commmunitypost',
            name='image',
            field=models.ImageField(default='abcd', upload_to='community_posts/'),
            preserve_default=False,
        ),
    ]
