# Generated by Django 4.0 on 2025-04-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_commmunitypost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commmunitypost',
            name='image',
        ),
    ]
