# Generated by Django 4.0 on 2025-04-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_commmunitypost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commmunitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_post/'),
        ),
    ]
