# Generated by Django 4.0 on 2025-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='css',
            field=models.TextField(default='abcd', verbose_name='CSS Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercises',
            name='html',
            field=models.TextField(default='a', verbose_name='HTML Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercises',
            name='js',
            field=models.TextField(default='c', verbose_name='JavaScript Code'),
            preserve_default=False,
        ),
    ]
