# Generated by Django 4.0 on 2025-04-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_exercises_css_exercises_html_exercises_js'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=270)),
                ('image', models.ImageField(upload_to='game_images/')),
                ('type', models.CharField(choices=[('1', 'Kids'), ('2', 'Students'), ('3', 'Both')], max_length=270)),
                ('css', models.TextField(verbose_name='CSS Code')),
                ('js', models.TextField(verbose_name='JavaScript Code')),
                ('html', models.TextField(verbose_name='HTML Code')),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='type',
            field=models.CharField(choices=[('1', 'Kids'), ('2', 'Students'), ('3', 'Both')], default='both', max_length=270),
            preserve_default=False,
        ),
    ]
