# Generated by Django 4.0 on 2025-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_games_exercises_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='type',
            field=models.CharField(choices=[('Kids', '1'), ('Students', '2'), ('Both', '3')], max_length=270),
        ),
        migrations.AlterField(
            model_name='games',
            name='type',
            field=models.CharField(choices=[('Kids', '1'), ('Students', '2'), ('Both', '3')], max_length=270),
        ),
    ]
