# Generated by Django 4.0 on 2025-04-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_exercises_type_alter_games_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='type',
            field=models.CharField(choices=[('1', 'Kids'), ('2', 'Students'), ('3', 'Both')], max_length=270),
        ),
        migrations.AlterField(
            model_name='games',
            name='type',
            field=models.CharField(choices=[('1', 'Kids'), ('2', 'Students'), ('3', 'Both')], max_length=270),
        ),
    ]
