# Generated by Django 4.0 on 2025-04-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KidsPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=270)),
                ('kids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='web.kids')),
            ],
        ),
    ]
