# Generated by Django 4.0 on 2025-04-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_kids_kidsplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsplay',
            name='value',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
