# Generated by Django 4.0 on 2025-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_kidsplay_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsplay',
            name='link',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
