# Generated by Django 4.0 on 2025-04-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_kidsplay_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=270, null=True)),
                ('link', models.CharField(blank=True, max_length=270, null=True)),
                ('kids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='web.student')),
            ],
        ),
    ]
