# Generated by Django 4.0 on 2025-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_student_studentplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='item',
            field=models.CharField(default='abcd', max_length=270),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='item',
            field=models.CharField(default='abcd', max_length=270),
            preserve_default=False,
        ),
    ]
